# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35c08b1937ed997dfaaa66d762d6bd7ee5389fe6ac81bec139f0c4a6c7b653573af683a7a9237a59b407eb8e9acab7475ec4f4f9c665333845733beba6139b61

test:
  secret_key_base: b235f1e551deddd230ac34a42be968750d77ffcc4550f1a35fb1ef790fabebac9b3e4868043d4434d442098518b6596f5ecf4ae72974194aa19ceae5b2e88344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
